<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '10a9f68ca932e091e5e85845923d10ec',
  'DATABASE_URL' => 'mysql://hajji:Zysos2901@mysql-hajji.alwaysdata.net:3306/hajji_za?serverVersion=mariadb-10.6',
);
