<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTTu6mHs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTTu6mHs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTTu6mHs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTTu6mHs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTTu6mHs\App_KernelDevDebugContainer([
    'container.build_hash' => 'TTu6mHs',
    'container.build_id' => '06df4c38',
    'container.build_time' => 1703074363,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTTu6mHs');
